site_name: SciEcon NFT Symposium Program
theme: 
  name: material
  logo: assets/logo1.png
  favicon: assets/images/logo2.png
  font:
    # text: Noto Sans
markdown_extensions:
  - attr_list
extra_css:
  - stylesheets/extra.css